//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnapIt.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnapIt.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string About {
            get { return ResourceManager.GetString("About", resourceCulture); }
        }
        internal static string AboutDescription {
            get { return ResourceManager.GetString("AboutDescription", resourceCulture); }
        }
        internal static string AllTopics {
            get { return ResourceManager.GetString("AllTopics", resourceCulture); }
        }
        internal static string ApplyChanges {
            get { return ResourceManager.GetString("ApplyChanges", resourceCulture); }
        }
        internal static string ApplyChangesQuestion {
            get { return ResourceManager.GetString("ApplyChangesQuestion", resourceCulture); }
        }
        internal static string AppDescription {
            get { return ResourceManager.GetString("AppDescription", resourceCulture); }
        }
        internal static string AppTheme {
            get { return ResourceManager.GetString("AppTheme", resourceCulture); }
        }
        internal static string AppliedFor {
            get { return ResourceManager.GetString("AppliedFor", resourceCulture); }
        }
        internal static string AreaTheme {
            get { return ResourceManager.GetString("AreaTheme", resourceCulture); }
        }
        internal static string BorderColor {
            get { return ResourceManager.GetString("BorderColor", resourceCulture); }
        }
        internal static string BorderThickness {
            get { return ResourceManager.GetString("BorderThickness", resourceCulture); }
        }
        internal static string ChangeLayouts {
            get { return ResourceManager.GetString("ChangeLayouts", resourceCulture); }
        }
        internal static string ChangeLayoutsDescription {
            get { return ResourceManager.GetString("ChangeLayoutsDescription", resourceCulture); }
        }
        internal static string CheckForNewVersion {
            get { return ResourceManager.GetString("CheckForNewVersion", resourceCulture); }
        }
        internal static string ConfigureAndUseApps {
            get { return ResourceManager.GetString("ConfigureAndUseApps", resourceCulture); }
        }
        internal static string ConfigureKeyboard {
            get { return ResourceManager.GetString("ConfigureKeyboard", resourceCulture); }
        }
        internal static string ConfigureMouse {
            get { return ResourceManager.GetString("ConfigureMouse", resourceCulture); }
        }
        internal static string ConfigureWindow {
            get { return ResourceManager.GetString("ConfigureWindow", resourceCulture); }
        }
        internal static string CurrentVersion {
            get { return ResourceManager.GetString("CurrentVersion", resourceCulture); }
        }
        internal static string CustomizeLayoutUI {
            get { return ResourceManager.GetString("CustomizeLayoutUI", resourceCulture); }
        }
        internal static string Dashboard {
            get { return ResourceManager.GetString("Dashboard", resourceCulture); }
        }
        internal static string DashboardDescription {
            get { return ResourceManager.GetString("DashboardDescription", resourceCulture); }
        }
        internal static string Delete {
            get { return ResourceManager.GetString("Delete", resourceCulture); }
        }
        internal static string DisableFullscreenSnapping {
            get { return ResourceManager.GetString("DisableFullscreenSnapping", resourceCulture); }
        }
        internal static string DisableModalSnapping {
            get { return ResourceManager.GetString("DisableModalSnapping", resourceCulture); }
        }
        internal static string DisableModalSnappingDescription {
            get { return ResourceManager.GetString("DisableModalSnappingDescription", resourceCulture); }
        }
        internal static string DisableWindowCornering {
            get { return ResourceManager.GetString("DisableWindowCornering", resourceCulture); }
        }
        internal static string DisableWindowCorneringDescription {
            get { return ResourceManager.GetString("DisableWindowCorneringDescription", resourceCulture); }
        }
        internal static string Display {
            get { return ResourceManager.GetString("Display", resourceCulture); }
        }
        internal static string Edit {
            get { return ResourceManager.GetString("Edit", resourceCulture); }
        }
        internal static string EnableMouseHoverAnimations {
            get { return ResourceManager.GetString("EnableMouseHoverAnimations", resourceCulture); }
        }
        internal static string Exclude {
            get { return ResourceManager.GetString("Exclude", resourceCulture); }
        }
        internal static string ExcludeWindowsDefaultModals {
            get { return ResourceManager.GetString("ExcludeWindowsDefaultModals", resourceCulture); }
        }
        internal static string ExcludeWindowsDefaultModalsDescription {
            get { return ResourceManager.GetString("ExcludeWindowsDefaultModalsDescription", resourceCulture); }
        }
        internal static string ExcludedApplications {
            get { return ResourceManager.GetString("ExcludedApplications", resourceCulture); }
        }
        internal static string ExcludedApplicationsDescription {
            get { return ResourceManager.GetString("ExcludedApplicationsDescription", resourceCulture); }
        }
        internal static string Exit {
            get { return ResourceManager.GetString("Exit", resourceCulture); }
        }
        internal static string Export {
            get { return ResourceManager.GetString("Export", resourceCulture); }
        }
        internal static string Feedback {
            get { return ResourceManager.GetString("Feedback", resourceCulture); }
        }
        internal static string GettingStarted {
            get { return ResourceManager.GetString("GettingStarted", resourceCulture); }
        }
        internal static string GiveFeedback {
            get { return ResourceManager.GetString("GiveFeedback", resourceCulture); }
        }
        internal static string GiveFeedbackDescription {
            get { return ResourceManager.GetString("GiveFeedbackDescription", resourceCulture); }
        }
        internal static string Github {
            get { return ResourceManager.GetString("Github", resourceCulture); }
        }
        internal static string HighlightColor {
            get { return ResourceManager.GetString("HighlightColor", resourceCulture); }
        }
        internal static string Home {
            get { return ResourceManager.GetString("Home", resourceCulture); }
        }
        internal static string HowToGetStarted {
            get { return ResourceManager.GetString("HowToGetStarted", resourceCulture); }
        }
        internal static string HowToUseAndConfigureApps {
            get { return ResourceManager.GetString("HowToUseAndConfigureApps", resourceCulture); }
        }
        internal static string Import {
            get { return ResourceManager.GetString("Import", resourceCulture); }
        }
        internal static string Introduction {
            get { return ResourceManager.GetString("Introduction", resourceCulture); }
        }
        internal static string Keyboard {
            get { return ResourceManager.GetString("Keyboard", resourceCulture); }
        }
        internal static string Keyword {
            get { return ResourceManager.GetString("Keyword", resourceCulture); }
        }
        internal static string Language {
            get { return ResourceManager.GetString("Language", resourceCulture); }
        }
        internal static string Layout {
            get { return ResourceManager.GetString("Layout", resourceCulture); }
        }
        internal static string LayoutName {
            get { return ResourceManager.GetString("LayoutName", resourceCulture); }
        }
        internal static string Layouts {
            get { return ResourceManager.GetString("Layouts", resourceCulture); }
        }
        internal static string LearnAndExplore {
            get { return ResourceManager.GetString("LearnAndExplore", resourceCulture); }
        }
        internal static string License {
            get { return ResourceManager.GetString("License", resourceCulture); }
        }
        internal static string Maintainer {
            get { return ResourceManager.GetString("Maintainer", resourceCulture); }
        }
        internal static string MatchRule {
            get { return ResourceManager.GetString("MatchRule", resourceCulture); }
        }
        internal static string Mouse {
            get { return ResourceManager.GetString("Mouse", resourceCulture); }
        }
        internal static string MouseHoverAnimationDescription {
            get { return ResourceManager.GetString("MouseHoverAnimationDescription", resourceCulture); }
        }
        internal static string New {
            get { return ResourceManager.GetString("New", resourceCulture); }
        }
        internal static string NewIdeasOrReportBug {
            get { return ResourceManager.GetString("NewIdeasOrReportBug", resourceCulture); }
        }
        internal static string OlderChanges {
            get { return ResourceManager.GetString("OlderChanges", resourceCulture); }
        }
        internal static string OpenInDesigner {
            get { return ResourceManager.GetString("OpenInDesigner", resourceCulture); }
        }
        internal static string OpenSource {
            get { return ResourceManager.GetString("OpenSource", resourceCulture); }
        }
        internal static string OpenSourceDescription {
            get { return ResourceManager.GetString("OpenSourceDescription", resourceCulture); }
        }
        internal static string OriginalAuthor {
            get { return ResourceManager.GetString("OriginalAuthor", resourceCulture); }
        }
        internal static string OtherTopics {
            get { return ResourceManager.GetString("OtherTopics", resourceCulture); }
        }
        internal static string OverallOpacity {
            get { return ResourceManager.GetString("OverallOpacity", resourceCulture); }
        }
        internal static string OverlayColor {
            get { return ResourceManager.GetString("OverlayColor", resourceCulture); }
        }
        internal static string Preview {
            get { return ResourceManager.GetString("Preview", resourceCulture); }
        }
        internal static string Primary {
            get { return ResourceManager.GetString("Primary", resourceCulture); }
        }
        internal static string PrivacyPolicy {
            get { return ResourceManager.GetString("PrivacyPolicy", resourceCulture); }
        }
        internal static string QuickTips {
            get { return ResourceManager.GetString("QuickTips", resourceCulture); }
        }
        internal static string RateAndReviewOnStore {
            get { return ResourceManager.GetString("RateAndReviewOnStore", resourceCulture); }
        }
        internal static string Rename {
            get { return ResourceManager.GetString("Rename", resourceCulture); }
        }
        internal static string RunAsAdministrator {
            get { return ResourceManager.GetString("RunAsAdministrator", resourceCulture); }
        }
        internal static string Running {
            get { return ResourceManager.GetString("Running", resourceCulture); }
        }
        internal static string Screens {
            get { return ResourceManager.GetString("Screens", resourceCulture); }
        }
        internal static string ScreensDescription {
            get { return ResourceManager.GetString("ScreensDescription", resourceCulture); }
        }
        internal static string Secondary {
            get { return ResourceManager.GetString("Secondary", resourceCulture); }
        }
        internal static string SelectAndEditLayouts {
            get { return ResourceManager.GetString("SelectAndEditLayouts", resourceCulture); }
        }
        internal static string SelectCreateAndEditLayouts {
            get { return ResourceManager.GetString("SelectCreateAndEditLayouts", resourceCulture); }
        }
        internal static string Settings {
            get { return ResourceManager.GetString("Settings", resourceCulture); }
        }
        internal static string SourceCode {
            get { return ResourceManager.GetString("SourceCode", resourceCulture); }
        }
        internal static string Start {
            get { return ResourceManager.GetString("Start", resourceCulture); }
        }
        internal static string StartSnapItMinimizedToTray {
            get { return ResourceManager.GetString("StartSnapItMinimizedToTray", resourceCulture); }
        }
        internal static string StartSnapItWhenIStartWindows {
            get { return ResourceManager.GetString("StartSnapItWhenIStartWindows", resourceCulture); }
        }
        internal static string Stop {
            get { return ResourceManager.GetString("Stop", resourceCulture); }
        }
        internal static string Stopped {
            get { return ResourceManager.GetString("Stopped", resourceCulture); }
        }
        internal static string Theme {
            get { return ResourceManager.GetString("Theme", resourceCulture); }
        }
        internal static string TrialVersion {
            get { return ResourceManager.GetString("TrialVersion", resourceCulture); }
        }
        internal static string Tutorials {
            get { return ResourceManager.GetString("Tutorials", resourceCulture); }
        }
        internal static string Version {
            get { return ResourceManager.GetString("Version", resourceCulture); }
        }
        internal static string WatchTutorial {
            get { return ResourceManager.GetString("WatchTutorial", resourceCulture); }
        }
        internal static string Website {
            get { return ResourceManager.GetString("Website", resourceCulture); }
        }
        internal static string WhatsNew {
            get { return ResourceManager.GetString("WhatsNew", resourceCulture); }
        }
        internal static string WhatsNewDescription {
            get { return ResourceManager.GetString("WhatsNewDescription", resourceCulture); }
        }
        internal static string Window {
            get { return ResourceManager.GetString("Window", resourceCulture); }
        }
        internal static string UseMouseToSnapWindow {
            get { return ResourceManager.GetString("UseMouseToSnapWindow", resourceCulture); }
        }
        internal static string DelayMovementToActivateSnapping {
            get { return ResourceManager.GetString("DelayMovementToActivateSnapping", resourceCulture); }
        }
        internal static string DelayMovementDisabledWhenHoldKeyInUse {
            get { return ResourceManager.GetString("DelayMovementDisabledWhenHoldKeyInUse", resourceCulture); }
        }
        internal static string OnlyUseWindowTitleToSnapWindow {
            get { return ResourceManager.GetString("OnlyUseWindowTitleToSnapWindow", resourceCulture); }
        }
        internal static string OnlyUseWindowTitleDescription {
            get { return ResourceManager.GetString("OnlyUseWindowTitleDescription", resourceCulture); }
        }
        internal static string MouseButtonForSnapping {
            get { return ResourceManager.GetString("MouseButtonForSnapping", resourceCulture); }
        }
        internal static string UseHoldKey {
            get { return ResourceManager.GetString("UseHoldKey", resourceCulture); }
        }
        internal static string HoldKey {
            get { return ResourceManager.GetString("HoldKey", resourceCulture); }
        }
        internal static string HoldKeyBehaviour {
            get { return ResourceManager.GetString("HoldKeyBehaviour", resourceCulture); }
        }
        internal static string UseKeyboardToSnapWindow {
            get { return ResourceManager.GetString("UseKeyboardToSnapWindow", resourceCulture); }
        }
        internal static string UseWinShortcutToSnapWindow {
            get { return ResourceManager.GetString("UseWinShortcutToSnapWindow", resourceCulture); }
        }
        internal static string OverrideDefaultShortcuts {
            get { return ResourceManager.GetString("OverrideDefaultShortcuts", resourceCulture); }
        }
        internal static string Apply {
            get { return ResourceManager.GetString("Apply", resourceCulture); }
        }
        internal static string KeyboardShortcuts {
            get { return ResourceManager.GetString("KeyboardShortcuts", resourceCulture); }
        }
        internal static string MoveUp {
            get { return ResourceManager.GetString("MoveUp", resourceCulture); }
        }
        internal static string MoveDown {
            get { return ResourceManager.GetString("MoveDown", resourceCulture); }
        }
        internal static string MoveLeft {
            get { return ResourceManager.GetString("MoveLeft", resourceCulture); }
        }
        internal static string MoveRight {
            get { return ResourceManager.GetString("MoveRight", resourceCulture); }
        }
        internal static string StartStopSnapIt {
            get { return ResourceManager.GetString("StartStopSnapIt", resourceCulture); }
        }
        internal static string CycleThroughLayouts {
            get { return ResourceManager.GetString("CycleThroughLayouts", resourceCulture); }
        }
    }
}
